description = 'inspection-service'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation platform('com.google.cloud:libraries-bom:26.51.0')
    implementation 'com.google.cloud:google-cloud-storage'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'com.h2database:h2'
}

springBoot {
    mainClass = 'com.cheche.inspection.InspectionServiceApplication'
}
